"""Build coarse alpha-occupancy grids for decorative artwork.

Usage: python3 tools/build_occupancy.py  (from product-studio/)
Writes src/design-library/occupancy.ts. A cell is "ink" when more than
INK_SHARE of its pixels have alpha above ALPHA_MIN. The composition engine uses
these grids to test real artwork footprints (not bounding boxes) against
protected page content.
"""
from PIL import Image

GRID = 32
ALPHA_MIN = 24
INK_SHARE = 0.02
ASSETS = {
    "jcs-floral-corner": "floral-corner.png",
    "jcs-floral-sprig": "floral-header.png",
    "jcs-floral-bouquet": "floral-bouquet.png",
    "jcs-accent-topo": "accent-topo.png",
    "jcs-accent-waves": "accent-waves.png",
    "jcs-accent-arcs": "accent-arcs.png",
    "jcs-accent-ribbon": "accent-ribbon.png",
    "jcs-accent-dots": "accent-dots.png",
    "jcs-accent-stripes": "accent-stripes.png",
}

def grid(path):
    a = Image.open(path).convert("RGBA").split()[3]
    w, h = a.size
    px = a.load()
    rows = []
    for gy in range(GRID):
        y0, y1 = gy * h // GRID, (gy + 1) * h // GRID
        bits = ""
        for gx in range(GRID):
            x0, x1 = gx * w // GRID, (gx + 1) * w // GRID
            n = ink = 0
            for y in range(y0, y1, max(1, (y1 - y0) // 12)):
                for x in range(x0, x1, max(1, (x1 - x0) // 12)):
                    n += 1
                    ink += px[x, y] > ALPHA_MIN
            bits += "1" if n and ink / n > INK_SHARE else "0"
        rows.append(bits)
    return rows

out = ["/**", " * GENERATED by tools/build_occupancy.py — do not edit.", f" * {GRID}×{GRID} alpha-occupancy grids (row-major, '1' = artwork ink).", " */",
       f"export const OCCUPANCY_GRID = {GRID};", "export const OCCUPANCY: Record<string, string[]> = {"]
for aid, f in ASSETS.items():
    rows = grid(f"src/design-library/assets/{f}")
    out.append(f'  "{aid}": [')
    out += [f'    "{r}",' for r in rows]
    out.append("  ],")
out.append("};")
open("src/design-library/occupancy.ts", "w").write("\n".join(out) + "\n")
print("ok")
